substitutions:
  _PURCHASE_MAX_ACTIVE: '3'
  _MAKE_PURCHASE_COOLDOWN: '10m'
  _CANCEL_PURCHASE_COOLDOWN: '10m'
  _GRPC_GO_LOG_SEVERITY_LEVEL: 'error'
  _GRPC_GO_LOG_VERBOSITY_LEVEL: '0'
  _ESI_USER_AGENT: 'etco-go default-user-agent'
  _STRUCTURE_INFO_WEB_REFRESH_TOKEN: 'BOOTSTRAP_UNSET'
  _CORPORATION_WEB_REFRESH_TOKEN: 'BOOTSTRAP_UNSET'
  _CCACHE_MAX_BYTES: '268435456'
  _REGION: 'us-central1'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'PURCHASE_MAX_ACTIVE=${_PURCHASE_MAX_ACTIVE}'
  - '--build-arg'
  - 'MAKE_PURCHASE_COOLDOWN=${_MAKE_PURCHASE_COOLDOWN}'
  - '--build-arg'
  - 'CANCEL_PURCHASE_COOLDOWN=${_CANCEL_PURCHASE_COOLDOWN}'
  - '--build-arg'
  - 'BOOTSTRAP_ADMIN_ID=${_BOOTSTRAP_ADMIN_ID}'
  - '--build-arg'
  - 'CORPORATION_ID=${_CORPORATION_ID}'
  - '--build-arg'
  - 'GRPC_GO_LOG_SEVERITY_LEVEL=${_GRPC_GO_LOG_SEVERITY_LEVEL}'
  - '--build-arg'
  - 'GRPC_GO_LOG_VERBOSITY_LEVEL=${_GRPC_GO_LOG_VERBOSITY_LEVEL}'
  - '--build-arg'
  - 'ESI_USER_AGENT=${_ESI_USER_AGENT}'
  - '--build-arg'
  - 'STRUCTURE_INFO_WEB_REFRESH_TOKEN=${_STRUCTURE_INFO_WEB_REFRESH_TOKEN}'
  - '--build-arg'
  - 'CORPORATION_WEB_REFRESH_TOKEN=${_CORPORATION_WEB_REFRESH_TOKEN}'
  - '--build-arg'
  - 'ESI_MARKETS_CLIENT_ID=${_ESI_MARKETS_CLIENT_ID}'
  - '--build-arg'
  - 'ESI_MARKETS_CLIENT_SECRET=${_ESI_MARKETS_CLIENT_SECRET}'
  - '--build-arg'
  - 'ESI_CORP_CLIENT_ID=${_ESI_CORP_CLIENT_ID}'
  - '--build-arg'
  - 'ESI_CORP_CLIENT_SECRET=${_ESI_CORP_CLIENT_SECRET}'
  - '--build-arg'
  - 'ESI_STRUCTURE_INFO_CLIENT_ID=${_ESI_STRUCTURE_INFO_CLIENT_ID}'
  - '--build-arg'
  - 'ESI_STRUCTURE_INFO_CLIENT_SECRET=${_ESI_STRUCTURE_INFO_CLIENT_SECRET}'
  - '--build-arg'
  - 'ESI_AUTH_CLIENT_ID=${_ESI_AUTH_CLIENT_ID}'
  - '--build-arg'
  - 'ESI_AUTH_CLIENT_SECRET=${_ESI_AUTH_CLIENT_SECRET}'
  - '--build-arg'
  - 'BUCKET_CREDS_JSON=${_BUCKET_CREDS_JSON}'
  - '--build-arg'
  - 'REMOTEDB_PROJECT_ID=${_REMOTEDB_PROJECT_ID}'
  - '--build-arg'
  - 'REMOTEDB_CREDS_JSON=${_REMOTEDB_CREDS_JSON}'
  - '--build-arg'
  - 'CCACHE_MAX_BYTES=${_CCACHE_MAX_BYTES}'
  - '--build-arg'
  - 'SCACHE_ADDRESS=${_SCACHE_ADDRESS}'
  - '-t'
  - 'gcr.io/$PROJECT_ID/etco-go:latest'
  - '-f'
  - 'Dockerfile'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/etco-go:latest'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'etco-go'
  - '--image'
  - 'gcr.io/$PROJECT_ID/etco-go:latest'
  - '--region'
  - '${_REGION}'
  - '--allow-unauthenticated' # TODO: remove this

images: ['gcr.io/$PROJECT_ID/etco-go:latest']

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
