# Program Behavior Configuration
ARG PURCHASE_MAX_ACTIVE='3'
ARG MAKE_PURCHASE_COOLDOWN='10m'
ARG CANCEL_PURCHASE_COOLDOWN='10m'
ARG BOOTSTRAP_ADMIN_ID
ARG CORPORATION_ID

# GRPC Configuration
ARG GRPC_GO_LOG_SEVERITY_LEVEL='error'
ARG GRPC_GO_LOG_VERBOSITY_LEVEL='0'

# ESI Configuration
ARG ESI_USER_AGENT='etco-go default-user-agent'
ARG STRUCTURE_INFO_WEB_REFRESH_TOKEN='BOOTSTRAP_UNSET'
ARG CORPORATION_WEB_REFRESH_TOKEN='BOOTSTRAP_UNSET'
ARG ESI_MARKETS_CLIENT_ID
ARG ESI_MARKETS_CLIENT_SECRET
ARG ESI_CORP_CLIENT_ID
ARG ESI_CORP_CLIENT_SECRET
ARG ESI_STRUCTURE_INFO_CLIENT_ID
ARG ESI_STRUCTURE_INFO_CLIENT_SECRET
ARG ESI_AUTH_CLIENT_ID
ARG ESI_AUTH_CLIENT_SECRET

# Bucket (GCP only for now) Configuration
ARG BUCKET_CREDS_JSON
# RemoteDB (Firestore only for now) Configuration
ARG REMOTEDB_PROJECT_ID
ARG REMOTEDB_CREDS_JSON

# Local Cache Configuration (256MB default)
ARG CCACHE_MAX_BYTES='268435456'
# Server Cache Configuration
ARG SCACHE_ADDRESS

# filebuilder
FROM golang:1.21.3 AS filebuilder

ENV PURCHASE_MAX_ACTIVE=$PURCHASE_MAX_ACTIVE
ENV CANCEL_PURCHASE_COOLDOWN=$CANCEL_PURCHASE_COOLDOWN
ENV BOOTSTRAP_ADMIN_ID=$BOOTSTRAP_ADMIN_ID
ENV CORPORATION_ID=$CORPORATION_ID
ENV ESI_USER_AGENT=$ESI_USER_AGENT
ENV STRUCTURE_INFO_WEB_REFRESH_TOKEN=$STRUCTURE_INFO_WEB_REFRESH_TOKEN
ENV CORPORATION_WEB_REFRESH_TOKEN=$CORPORATION_WEB_REFRESH_TOKEN
ENV ESI_MARKETS_CLIENT_ID=$ESI_MARKETS_CLIENT_ID
ENV ESI_MARKETS_CLIENT_SECRET=$ESI_MARKETS_CLIENT_SECRET
ENV ESI_CORP_CLIENT_ID=$ESI_CORP_CLIENT_ID
ENV ESI_CORP_CLIENT_SECRET=$ESI_CORP_CLIENT_SECRET
ENV ESI_STRUCTURE_INFO_CLIENT_ID=$ESI_STRUCTURE_INFO_CLIENT_ID
ENV ESI_STRUCTURE_INFO_CLIENT_SECRET=$ESI_STRUCTURE_INFO_CLIENT_SECRET
ENV ESI_AUTH_CLIENT_ID=$ESI_AUTH_CLIENT_ID
ENV ESI_AUTH_CLIENT_SECRET=$ESI_AUTH_CLIENT_SECRET
ENV BUCKET_CREDS_JSON=$BUCKET_CREDS_JSON
ENV REMOTEDB_PROJECT_ID=$REMOTEDB_PROJECT_ID
ENV REMOTEDB_CREDS_JSON=$REMOTEDB_CREDS_JSON
ENV CCACHE_MAX_BYTES=$CCACHE_MAX_BYTES
ENV SCACHE_ADDRESS=$SCACHE_ADDRESS

ENV GOB_FILE_DIR='/root/out/gob'
ENV CONSTANTS_FILE_PATH='/root/out/buildconstants/buildconstants.go'

COPY etco-go-bucket/ /root/etco-go-bucket/
COPY etco-go-builder/ /root/etco-go-builder/
WORKDIR /root/etco-go-builder

RUN go run .

# builder
FROM golang:1.21.3 AS builder

COPY --from=filebuilder /root/out/buildconstants/buildconstants.go /root/etco-go/buildconstants/buildconstants.go
COPY etco-go-bucket/ /root/etco-go-bucket/
COPY etco-go/ /root/etco-go/
WORKDIR /root/etco-go-builder

RUN go build -o /root/out/bin .

# binary container
FROM alpine:3.18.4

ENV GRPC_GO_LOG_SEVERITY_LEVEL=$GRPC_GO_LOG_SEVERITY_LEVEL
ENV GRPC_GO_LOG_VERBOSITY_LEVEL=$GRPC_GO_LOG_VERBOSITY_LEVEL

RUN apk add --no-cache ca-certificates
RUN apk add --no-cache libc6-compat

COPY --from=builder /root/out/bin /root/bin
COPY --from=filebuilder /root/out/gob/ /root/
WORKDIR /root

CMD ["/root/bin"]
