substitutions:
  _ESI_USER_AGENT: 'etco-go-updater default-user-agent'
  _REGION: 'us-central1'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'ESI_USER_AGENT=${_ESI_USER_AGENT}'
  - '--build-arg'
  - 'BUCKET_CREDS_JSON=${_BUCKET_CREDS_JSON}'
  - '-t'
  - 'gcr.io/$PROJECT_ID/etco-go-updater:latest'
  - '-f'
  - 'Updater.Dockerfile'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/etco-go-updater:latest'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'jobs'
  - 'deploy'
  - 'etco-go-updater'
  - '--image'
  - 'gcr.io/$PROJECT_ID/etco-go-updater:latest'
  - '--region'
  - '${_REGION}'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    PROJECT_NUMBER=$(gcloud projects describe $(gcloud config get-value project) --format='value(projectNumber)')
    gcloud scheduler jobs create http etco-go-updater-schedulerjob \
      --location="${_REGION}" \
      --schedule="0 12 * * *" \
      --http-method="POST" \
      --uri="https://${_REGION}-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/$PROJECT_ID/jobs/etco-go-updater:run" \
      --oauth-service-account-email="${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"

images: ['gcr.io/$PROJECT_ID/etco-go-updater:latest']

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
