package etcogobucket

type CoreUpdaterData struct {
	CHECKSUM_WEB_BUYBACK_SYSTEM_TYPE_MAPS_BUILDER string
	CHECKSUM_WEB_SHOP_LOCATION_TYPE_MAPS_BUILDER  string
	CHECKSUM_WEB_BUYBACK_SYSTEMS                  string
	CHECKSUM_WEB_SHOP_LOCATIONS                   string
	CHECKSUM_WEB_MARKETS                          string
	CHECKSUM_WEB_HAUL_ROUTE_TYPE_MAPS_BUILDER     string
	CHECKSUM_WEB_HAUL_ROUTES                      string

	CAPACITY_WEB_BUYBACK_SYSTEM_TYPE_MAPS_BUILDER int
	CAPACITY_WEB_SHOP_LOCATION_TYPE_MAPS_BUILDER  int
	CAPACITY_WEB_BUYBACK_SYSTEMS                  int
	CAPACITY_WEB_SHOP_LOCATIONS                   int
	CAPACITY_WEB_MARKETS                          int
	CAPACITY_WEB_HAUL_ROUTE_TYPE_MAPS_BUILDER     int
	CAPACITY_WEB_HAUL_ROUTES                      int

	CAPACITY_CORE_BUYBACK_SYSTEM_TYPE_MAPS int
	CAPACITY_CORE_SHOP_LOCATION_TYPE_MAPS  int
	CAPACITY_CORE_BUYBACK_SYSTEMS          int
	CAPACITY_CORE_SHOP_LOCATIONS           int
	CAPACITY_CORE_MARKETS                  int
	CAPACITY_CORE_BANNED_FLAG_SETS         int
	CAPACITY_CORE_PRICINGS                 int
	CAPACITY_CORE_HAUL_ROUTE_TYPE_MAPS     int
	CAPACITY_CORE_HAUL_ROUTES              int
	CAPACITY_CORE_HAUL_ROUTE_INFOS         int

	VERSION_BUYBACK string
	VERSION_SHOP    string
}

type SDEUpdaterData struct {
	CHECKSUM_SDE string // checksum for the entire SDE

	CAPACITY_SDE_CATEGORIES      int
	CAPACITY_SDE_GROUPS          int
	CAPACITY_SDE_MARKET_GROUPS   int
	CAPACITY_SDE_NAME_TO_TYPE_ID int
	CAPACITY_SDE_REGIONS         int
	CAPACITY_SDE_SYSTEMS         int
	CAPACITY_SDE_SYSTEM_IDS      int
	CAPACITY_SDE_STATIONS        int
	CAPACITY_SDE_TYPE_DATA_MAP   int
	CAPACITY_SDE_TYPE_VOLUMES    int
}
